spring.application.name=frontend
server.address=0.0.0.0
server.port=${PORT:3000}

api.gateway.url=${API_GATEWAY_URL:http://localhost:8080}

spring.thymeleaf.cache=false
management.endpoints.web.exposure.include=health,info
